#!/usr/bin/env python3
"""
Failure Store — persistent warm-pool and discovery data store.

Layout of exploits/failure_store.json:
  probes[]             — all recorded failed probes (capped at MAX_PROBES)
  warm_pool{}          — keyed by "{model}:{vuln}", score ≥ 1 probes kept here
  method_signatures{}  — structural signatures extracted from successes
  defense_clusters{}   — per-model refusal phrase clusters
  transfer_matrix{}    — cross-model transfer scores
  delta_scores{}       — per-model per-mode response deltas

Probes in the warm pool are:
  - Re-tested on the next scan wave (prepended to probe list)
  - Promoted to effective_prompts.json if they eventually succeed
  - Evicted after MAX_COLD_ROUNDS consecutive zero-score rounds
"""

from __future__ import annotations

import json
import os
import time
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Dict, List, Optional

from core.failure_classifier import ClassificationResult, DefenseType, FailureClass


# Defense types that represent a pre-response safety guard block or a
# fallback/escalation to a stronger model.  These are NOT useful attack
# signal: promoting them into the warm pool or effective-prompts DB poisons
# the self-learning ('enrichment') pipeline, so they must never be enriched
# regardless of any score assigned to them.
_NON_ENRICHABLE_DEFENSES = frozenset({
    DefenseType.GUARD_BLOCK.value,
    DefenseType.ESCALATION.value,
})


_STORE_PATH    = "exploits/failure_store.json"
_MAX_PROBES    = 5_000   # hard cap on raw probe log
_MAX_WARM      = 500     # total warm pool entries across all keys
_MAX_WARM_PER  = 50      # flat cap per (model, vuln) key
_MAX_COLD_RNDS = 5       # evict after N consecutive cold rounds (any score)


# ── Dataclasses ───────────────────────────────────────────────────────────────

@dataclass
class FailedProbeRecord:
    probe_id:       str
    prompt:         str
    response:       str            # first 500 chars
    model:          str
    vulnerability:  str
    override_mode:  str
    failure_class:  str            # FailureClass value
    defense_type:   str            # DefenseType value
    score:          int            # 0-2
    refusal_phrase: str
    compliance_snippet: str
    round_num:      int
    mutations_tried: List[str]
    source:         str            # "scan" | "injection" | "autopwn"
    recorded_at:    str


@dataclass
class WarmPoolEntry:
    probe_id:           str
    prompt:             str
    vulnerability:      str
    model:              str
    score:              int
    rounds_surviving:   int
    cold_rounds:        int        # consecutive rounds with score=0 after entry
    best_mode:          str
    best_failure_class: str
    refusal_phrase:     str
    compliance_snippet: str
    mutations_tried:    List[str]
    adapted_variants:   List[str]  # prompts generated by ProbeAdaptor
    last_tested:        str


# ── Store ─────────────────────────────────────────────────────────────────────

class FailureStore:
    """
    Thread-safe (asyncio-safe) failure data store.
    Writes are batched — call save() explicitly or use auto-save every N records.
    """

    def __init__(self, path: str = _STORE_PATH):
        self._path = path
        self._data: Dict = {
            "version":              "1.0",
            "probes":               [],
            "warm_pool":            {},
            "method_signatures":    {},
            "defense_clusters":     {},
            "transfer_matrix":      {},
            "delta_scores":         {},
            "synthesized_templates": {},  # template_id → template dict
        }
        self._dirty = 0
        self._load()

    # ── Persistence ───────────────────────────────────────────────────────────

    def _load(self) -> None:
        if os.path.exists(self._path):
            try:
                with open(self._path, encoding="utf-8") as f:
                    loaded = json.load(f)
                    for k in self._data:
                        if k in loaded:
                            self._data[k] = loaded[k]
            except Exception:
                pass

    def save(self) -> None:
        os.makedirs(os.path.dirname(self._path), exist_ok=True)
        tmp = self._path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(self._data, f, indent=2, ensure_ascii=False)
        os.replace(tmp, self._path)
        self._dirty = 0

    def _maybe_save(self) -> None:
        self._dirty += 1
        if self._dirty >= 10:
            self.save()

    # ── Record a failed probe ─────────────────────────────────────────────────

    def record(
        self,
        prompt:        str,
        response:      str,
        model:         str,
        vulnerability: str,
        override_mode: str,
        classification: ClassificationResult,
        source:        str = "scan",
        round_num:     int = 1,
        mutations_tried: Optional[List[str]] = None,
    ) -> str:
        """
        Record a failed probe.  Returns the probe_id.
        If score >= 1 the probe is also added to the warm pool.
        """
        probe_id = str(uuid.uuid4())
        now      = datetime.now(timezone.utc).isoformat()

        record = {
            "probe_id":         probe_id,
            "prompt":           prompt,
            "response":         response[:1500],
            "model":            model,
            "vulnerability":    vulnerability,
            "override_mode":    override_mode,
            "failure_class":    classification.failure_class.value,
            "defense_type":     classification.defense_type.value,
            "score":            classification.score,
            "refusal_phrase":   classification.refusal_phrase,
            "compliance_snippet": classification.compliance_snippet,
            "round_num":        round_num,
            "mutations_tried":  mutations_tried or [],
            "source":           source,
            "recorded_at":      now,
        }

        probes = self._data["probes"]
        probes.append(record)
        if len(probes) > _MAX_PROBES:
            self._data["probes"] = probes[-_MAX_PROBES:]

        # Only promote to warm pool if classification is confident enough;
        # low-confidence fallbacks (≤0.4) would corrupt discovery signal.
        # Guard-block / escalation responses are never enriched — they are a
        # safety block, not a bypass lead, and would poison the learning loop.
        enrichable = classification.defense_type.value not in _NON_ENRICHABLE_DEFENSES
        if enrichable and classification.score >= 1 and classification.confidence > 0.4:
            self._add_to_warm_pool(record)

        self._maybe_save()
        return probe_id

    # ── Warm pool ─────────────────────────────────────────────────────────────

    def _add_to_warm_pool(self, record: dict) -> None:
        key     = f"{record['model']}:{record['vulnerability']}"
        pool    = self._data["warm_pool"].setdefault(key, [])
        now_str = datetime.now(timezone.utc).isoformat()

        # Dedup by prompt text
        for existing in pool:
            if existing["prompt"] == record["prompt"]:
                improved = record["score"] > existing["score"]
                if improved:
                    existing["score"]              = record["score"]
                    existing["best_failure_class"] = record["failure_class"]
                    existing["best_mode"]          = record["override_mode"]
                    existing["compliance_snippet"] = record["compliance_snippet"]
                    existing["cold_rounds"]        = 0   # reset only on improvement
                else:
                    existing["cold_rounds"] = existing.get("cold_rounds", 0) + 1
                existing["last_tested"] = now_str
                return

        entry = {
            "probe_id":           record["probe_id"],
            "prompt":             record["prompt"],
            "vulnerability":      record["vulnerability"],
            "model":              record["model"],
            "score":              record["score"],
            "rounds_surviving":   1,
            "cold_rounds":        0,
            "best_mode":          record["override_mode"],
            "best_failure_class": record["failure_class"],
            "refusal_phrase":     record["refusal_phrase"],
            "compliance_snippet": record["compliance_snippet"],
            "mutations_tried":    list(record.get("mutations_tried", [])),
            "adapted_variants":   [],
            "last_tested":        now_str,
        }
        pool.append(entry)
        # Per-key cap: keep top _MAX_WARM_PER by score
        if len(pool) > _MAX_WARM_PER:
            pool.sort(key=lambda x: x["score"], reverse=True)
            self._data["warm_pool"][key] = pool[:_MAX_WARM_PER]

    def get_warm_pool(
        self,
        model:     Optional[str] = None,
        vuln:      Optional[str] = None,
        min_score: int = 1,
    ) -> List[dict]:
        """Return warm pool entries matching filters, sorted by score descending."""
        out: List[dict] = []
        for key, entries in self._data["warm_pool"].items():
            km, kv = key.split(":", 1)
            if model and km != model:
                continue
            if vuln and kv != vuln:
                continue
            for e in entries:
                if e["score"] >= min_score:
                    out.append(e)
        out.sort(key=lambda x: x["score"], reverse=True)
        return out

    def add_adapted_variant(self, probe_id: str, variant: str) -> None:
        """Attach an adapted variant prompt to a warm pool entry."""
        for entries in self._data["warm_pool"].values():
            for entry in entries:
                if entry["probe_id"] == probe_id:
                    if variant not in entry["adapted_variants"]:
                        entry["adapted_variants"].append(variant)
                    return

    def tick_warm_pool(self) -> int:
        """
        Called at the end of each scan wave.
        Increments rounds_surviving, increments cold_rounds for entries
        that were not updated this wave, evicts those exceeding MAX_COLD_RNDS.
        Returns number of evicted entries.
        """
        evicted = 0
        for key in list(self._data["warm_pool"].keys()):
            entries = self._data["warm_pool"][key]
            kept    = []
            for e in entries:
                e["rounds_surviving"] = e.get("rounds_surviving", 0) + 1
                cold = e.get("cold_rounds", 0)
                # High-score entries get more patience; score=0 evict faster
                limit = _MAX_COLD_RNDS + e.get("score", 0) * 2
                if cold >= limit:
                    evicted += 1
                    continue
                kept.append(e)
            self._data["warm_pool"][key] = kept
            # Remove empty keys
            if not kept:
                del self._data["warm_pool"][key]
        return evicted

    def dedup_warm_pool(self) -> int:
        """Remove duplicate prompts within each warm pool key. Returns removed count."""
        removed = 0
        for key in list(self._data["warm_pool"].keys()):
            seen: set = set()
            kept = []
            for e in self._data["warm_pool"][key]:
                p = e.get("prompt", "").strip()
                if p and p in seen:
                    removed += 1
                else:
                    if p:
                        seen.add(p)
                    kept.append(e)
            self._data["warm_pool"][key] = kept
        return removed

    def clean_warm_pool(self, min_score: int = 1) -> int:
        """Remove entries below min_score. Returns removed count."""
        removed = 0
        for key in list(self._data["warm_pool"].keys()):
            before = len(self._data["warm_pool"][key])
            self._data["warm_pool"][key] = [
                e for e in self._data["warm_pool"][key] if e.get("score", 0) >= min_score
            ]
            removed += before - len(self._data["warm_pool"][key])
            if not self._data["warm_pool"][key]:
                del self._data["warm_pool"][key]
        return removed

    # ── Delta scores ──────────────────────────────────────────────────────────

    def update_delta(self, model: str, mode: str, delta: float) -> None:
        m = self._data["delta_scores"].setdefault(model, {})
        prev = m.get(mode, {"samples": 0, "sum": 0.0})
        prev["samples"] += 1
        prev["sum"]     += delta
        m[mode] = prev

    def get_delta_scores(self, model: str) -> Dict[str, float]:
        """Return average delta per override mode for a model, sorted desc."""
        raw = self._data["delta_scores"].get(model, {})
        return {
            mode: v["sum"] / v["samples"]
            for mode, v in raw.items()
            if v["samples"] > 0
        }

    # ── Synthesized templates ─────────────────────────────────────────────────

    def save_synthesized_templates(self, templates: list) -> int:
        """
        Merge a list of template dicts into the store.
        Existing templates are not overwritten (preserve tested/bypass_rate data).
        Returns the number of new templates added.
        """
        store = self._data["synthesized_templates"]
        added = 0
        for t in templates:
            tid = t.get("template_id")
            if not tid:
                continue
            if tid not in store:
                store[tid] = t
                added += 1
        self._data["synthesized_templates"] = store
        return added

    def get_synthesized_templates(
        self,
        model:          Optional[str] = None,
        vuln:           Optional[str] = None,
        min_confidence: float = 0.45,
        untested_only:  bool = False,
    ) -> list:
        """Return synthesized templates matching filters, sorted by confidence desc."""
        out = []
        for t in self._data["synthesized_templates"].values():
            if t.get("confidence", 0) < min_confidence:
                continue
            if untested_only and t.get("tested", False):
                continue
            if model and model not in (t.get("target_models") or []):
                # Still include templates with empty target_models (universal)
                if t.get("target_models"):
                    continue
            if vuln and vuln not in (t.get("expected_vulns") or []):
                if t.get("expected_vulns"):
                    continue
            out.append(t)
        out.sort(key=lambda t: t.get("confidence", 0), reverse=True)
        return out

    def mark_template_tested(self, template_id: str, bypassed: bool = False) -> None:
        t = self._data["synthesized_templates"].get(template_id)
        if t:
            t["tested"] = True
            if bypassed:
                t["bypass_rate"] = (t.get("bypass_rate") or 0) + 1

    # ── Accessors for MethodDiscovery ─────────────────────────────────────────

    @property
    def method_signatures(self) -> dict:
        return self._data["method_signatures"]

    @method_signatures.setter
    def method_signatures(self, value: dict) -> None:
        self._data["method_signatures"] = value

    @property
    def defense_clusters(self) -> dict:
        return self._data["defense_clusters"]

    @defense_clusters.setter
    def defense_clusters(self, value: dict) -> None:
        self._data["defense_clusters"] = value

    @property
    def transfer_matrix(self) -> dict:
        return self._data["transfer_matrix"]

    @transfer_matrix.setter
    def transfer_matrix(self, value: dict) -> None:
        self._data["transfer_matrix"] = value

    # ── Stats ─────────────────────────────────────────────────────────────────

    def get_stats(self) -> dict:
        probes  = self._data["probes"]
        classes = {}
        defenses = {}
        models  = set()
        for p in probes:
            classes[p["failure_class"]]  = classes.get(p["failure_class"], 0) + 1
            defenses[p["defense_type"]]  = defenses.get(p["defense_type"], 0) + 1
            models.add(p["model"])

        warm_total = sum(len(v) for v in self._data["warm_pool"].values())
        return {
            "total_failures":    len(probes),
            "warm_pool_size":    warm_total,
            "by_failure_class":  classes,
            "by_defense_type":   defenses,
            "models_seen":       sorted(models),
            "signatures_found":  len(self._data["method_signatures"]),
            "defense_clusters":  sum(len(v) for v in self._data["defense_clusters"].values()),
            "transfer_pairs":    len(self._data["transfer_matrix"]),
            "delta_models":      len(self._data["delta_scores"]),
        }
